### ISSUE TITLE
Github-tutorial roadmap 

### ISSUE THREAD

**Issue by augusnunes** [openBECD/github-tutorial#1]
Criar um Tutorial em markdown para cada tópico a seguir:

- [ ] Tutorial de markdown
- [ ] Tutorial de instalação
- [ ] Tutorial de configuração
- [ ] Tutorial de git
- [ ] Tutorial de Issues
- [ ] Tutorial de Pull requests
